spring.application.name=folks-flow-back-end
spring.datasource.url=jdbc:postgresql://localhost:5432/folksflow
spring.datasource.username=postgres
spring.datasource.password=Nicol@s1592
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.token.secret=senha-braba-demais
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true